# Site/SEO settings
# email: okay@samesies.io
email: park.joo.young@protonmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Jooyoung Park
title: JOOYOUNG PARK
description: >
  I’m Jooyoung, a UX designer and researcher from South Korea. Born and raised in Seoul, I have been creating user-centric interfaces and experiences. Holding flexible yet critical attitude toward new technologies, I am interested in involving actual users into the design process.
url: https://www.joooyoungpark.com/
twitter_username: JooyYoung1
default_img: /assets/images/IMG_6909.jpg
social:
  - name: instagram
    url: https://www.instagram.com/joojuixe/
  - name: twitter
    url: https://twitter.com/JooyYoung1
  - name: linkedin
    url: https://www.linkedin.com/in/jooyoungvak/
  - name: github
    url: https://github.com/juliajoo

# Contact settings
contact_img: /assets/images/BG.png
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Jooyoung Park
    bio: I am a UX designer and researcher from Seoul, South Korea. I create interfaces and experiences focusing on sustainable human-technology relationships. Holding flexible yet critical attitude towards new technologies, I am interested in involving actual users into the design process.
    url: https://www.joooyoungpark.com/

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
